version: '2'
services:
  test-runner:
    image: node
    container_name: te_front_end_tests
    volumes:
      - "${WORKSPACE}:/translationExchange"
      - ./scripts:/scripts
    command: bash -c "cd /translationExchange
                      && npm install
                      && rm /translationExchange/node_modules/react-mic-plus/lib/libs/AudioContext.js
                      && cp /scripts/AudioContext.js /translationExchange/node_modules/react-mic-plus/lib/libs/AudioContext.js
                      && npm run test:ci --silent"
    network_mode: "host"
