version: '2'
services:
  test-runner:
    image: node
    container_name: te_front_end_tests
    env_file:
      - ./test-runner.env
    environment:
      - COVERALLS_REPO_TOKEN
    volumes:
      - "${PROJ_DIR}:${PROJ_DIR}"
      - ./scripts:/scripts
    command: bash -c "chmod +x /scripts/run-tests.sh
                      && /scripts/run-tests.sh"
    network_mode: "host"

#&& cat src/__test__/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
