# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=250)),
                ('duration', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('checked_level', models.IntegerField(default=0)),
                ('project_id', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anthology', models.CharField(max_length=2)),
                ('language', models.CharField(max_length=20)),
                ('version', models.CharField(max_length=3)),
                ('slug', models.CharField(max_length=3)),
                ('book_number', models.IntegerField(default=0)),
                ('mode', models.CharField(max_length=10)),
                ('chapter', models.IntegerField(default=0)),
                ('startv', models.IntegerField(default=0)),
                ('endv', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('agreed', models.BooleanField()),
                ('picture', models.CharField(max_length=250)),
            ],
        ),
    ]
