# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170627_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.File'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='markers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
