# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 03:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170628_2107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='Take',
        ),
        migrations.RemoveField(
            model_name='meta',
            name='file',
        ),
        migrations.AddField(
            model_name='meta',
            name='take',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Take'),
        ),
    ]
