# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170627_1535'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Language',
        ),
    ]
