# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170629_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='take',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
    ]
