# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_20170627_1648'),
        ('api', '0004_auto_20170627_1658'),
    ]

    operations = [
    ]
