export const PLAY_PAUSE_SELECTED_TAKE='PLAY_PAUSE_SELECTED_TAKE';
export const PAUSE_SELECTED_TAKE='PAUSE_SELECTED_TAKE';
export const LOADING='LOADING';
export const FETCH_ALTERNATE_TAKES='FETCH_ALTERNATE_TAKES';
export const FETCH_CHUNKS='FETCH_CHUNKS';
export const UPDATE_ACTIVE_CHUNK_INDEX = 'UPDATE_ACTIVE_CHUNK_INDEX';
